# Generated by Django 4.2.5 on 2023-09-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_location_alter_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
