# Generated by Django 4.2.5 on 2023-09-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
